version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
    groups:
      python-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
