name: CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: victron-venus/venus-os-ci-toolkit/.github/workflows/python-ci.yml@ba44ba6d9b63e884a5bde2dd30a990bb434cfe74  # main
    with:
      force-full: true
      python-version: '3.11'
      coverage-artifact-name: coverage-python
