name: CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: victron-venus/venus-os-ci-toolkit/.github/workflows/python-ci.yml@549ccf1ccf5cdc59fb04774e1d129277e6d91c38  # main
    with:
      force-full: true
      use-uv-lock: true
      python-version: '3.11'
      coverage-artifact-name: coverage-python
