name: CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: victron-venus/venus-os-ci-toolkit/.github/workflows/python-ci.yml@dceed6ce56af841f729297eec10129a61fd44df9  # main
    with:
      force-full: true
      python-version: '3.11'
      coverage-artifact-name: coverage-python
